### ISSUE TITLE
Feature Request: Visual Indicator of Turn Ending

### ISSUE THREAD

**Issue by Cadspen** [Squalm/GoClock#3]
It'd be nice if when you click on the clock to end your turn that it highlighted the clock like a button.  I wasn't confident that the clock was working until the clock actually started ticking after pressing it, but having some sort of visual indicator that you've pressed the clock would make it feel a lot better overall.

**Comment by Squalm** [comment]
Doesn't sound too hard, so I'll get right to it. Thanks!

**Comment by Squalm** [comment]
Ok just added a little colour indicator when you click. I've already got an item on my to do list for this site to add sounds which should make it even clearer. If that's all good with you (or in a day or two if you don't respond) I'll close this issue.
